# create two images, node and mongo
services:
  node:
    build:
      context: .
      target: node-img
    ports:
      - 3000:3000
    image: node-img
    container_name: node-container
    networks:
      - app-network
    environment:
      - DB_HOSTNAME=postgres-container
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
  postgres:
    # just pull the Postgres image
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - app-network
    container_name: postgres-container
    # start this AFTER node img
    depends_on:
      - node
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
  dotnet-sdk:
    # pulls dotnet sdk 9
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: dotnet-sdk-container
    stdin_open: true
    tty: true
  dotnet-aspnet:
    # pulls aspnet 9 runtime
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    networks:
      - app-network
    container_name: dotnet-aspnet-container
    stdin_open: true
    tty: true
  pgadmin:
    # only run this in dev
    # docker-compose --profile dev up
    image: dpage/pgadmin4:latest
    ports:
      - ${PGADMIN_PORT}:80
    container_name: pgadmin-container
    stdin_open: true
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    profiles:
      - dev


# connect all containers to this network
networks:
  app-network:
    name: app-network
